<?php

namespace NextDeveloper\IAM\Services;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use NextDeveloper\Commons\Database\GlobalScopes\LimitScope;
use NextDeveloper\Commons\Helpers\DatabaseHelper;
use NextDeveloper\Events\Services\Events;
use NextDeveloper\IAM\Database\Filters\UserRolesQueryFilter;
use NextDeveloper\IAM\Database\Models\RoleUsers;
use NextDeveloper\IAM\Database\Models\UserRoles;
use NextDeveloper\IAM\Database\Scopes\AuthorizationScope;
use NextDeveloper\IAM\Helpers\UserHelper;
use NextDeveloper\IAM\Services\AbstractServices\AbstractUserRolesService;

/**
 * This class is responsible from managing the data for UserRoles
 *
 * Class UserRolesService.
 *
 * @package NextDeveloper\IAM\Database\Models
 */
class UserRolesService extends AbstractUserRolesService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function get(UserRolesQueryFilter $filter = null, array $params = []) : Collection|LengthAwarePaginator{
        $roles = UserRoles::withoutGlobalScope(AuthorizationScope::class)
            ->withoutGlobalScope(LimitScope::class)
            ->filter($filter)
            ->where('iam_account_id', UserHelper::currentAccount()->id)
            ->get();

        return $roles;
    }

    public static function create(array $data)
    {
        //  Here we should check privileges not to create faulty role.

        if (array_key_exists('iam_role_id', $data)) {
            $data['iam_role_id'] = DatabaseHelper::uuidToId(
                '\NextDeveloper\IAM\Database\Models\Roles',
                $data['iam_role_id']
            );
        }
        if (array_key_exists('iam_user_id', $data)) {
            $data['iam_user_id'] = DatabaseHelper::uuidToId(
                '\NextDeveloper\IAM\Database\Models\Users',
                $data['iam_user_id']
            );
        }

        if(!array_key_exists('iam_user_id', $data)) {
            $data['iam_user_id']    = UserHelper::me()->id;
        }
        if (array_key_exists('iam_account_id', $data)) {
            $data['iam_account_id'] = DatabaseHelper::uuidToId(
                '\NextDeveloper\IAM\Database\Models\Accounts',
                $data['iam_account_id']
            );
        }

        if(!array_key_exists('iam_account_id', $data)) {
            $data['iam_account_id'] = UserHelper::currentAccount()->id;
        }

        try {
            $model = RoleUsers::create($data);
        } catch(\Exception $e) {
            throw $e;
        }

        Events::fire('created:NextDeveloper\IAM\UserRoles', $model);

        return $model->fresh();

        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
