<?php

namespace NextDeveloper\IAM\Database\Abstract;

use Illuminate\Database\Eloquent\Model;

class AuthorizationModel extends Model
{

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
